export interface Promotion{
  vacancyId: string,
  positionId: string,
  levelId: string,
  empId: string,
  startDate: string,
    status:Number,
    pId:number,
    id: string,
  createdBy?: String, 
    createdDate?: String, 
    updatedDate: String, 
    updatedBy: String, 
}
export interface PromotionRelation{
  vacancyId: string,
  approvedDate: string,
  promotionStatus:string,
  empId: string,
    status:Number,
    pId:number,
    id: string,
  createdBy?: String, 
    createdDate?: String, 
    updatedDate: String, 
    updatedBy: String, 
}